# Generated by Django 4.2.11 on 2026-04-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frame_number', models.IntegerField()),
                ('duration_ms', models.FloatField()),
                ('frame_data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Analyse Frame',
                'verbose_name_plural': 'Analyses Frame',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('error', 'Erreur'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('max_fps', models.IntegerField(default=30)),
                ('resolution', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2K', '2K'), ('4K', '4K')], default='1080p', max_length=10)),
                ('audio_alerts', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('storage_limit_gb', models.IntegerField(default=100)),
                ('retention_days', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configuration Système',
            },
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_detection', models.DateTimeField(blank=True, null=True)),
                ('detection_count', models.IntegerField(default=0)),
                ('alert_count', models.IntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='app.module')),
            ],
            options={
                'verbose_name': 'Statut Module',
                'verbose_name_plural': 'Statuts Module',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('map_score', models.FloatField(default=0.0)),
                ('fps', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('custom_metrics', models.JSONField(default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='app.module')),
            ],
            options={
                'verbose_name': 'Métrique',
                'verbose_name_plural': 'Métriques',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('system_start', 'Démarrage Système'), ('system_stop', 'Arrêt Système'), ('alert_generated', 'Alerte Générée'), ('module_error', 'Erreur Module'), ('config_changed', 'Configuration Modifiée'), ('model_loaded', 'Modèle Chargé')], max_length=50)),
                ('description', models.TextField()),
                ('user', models.CharField(default='System', max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.module')),
            ],
            options={
                'verbose_name': 'Journal Événement',
                'verbose_name_plural': 'Journaux Événement',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='app.module')),
            ],
            options={
                'verbose_name': 'Détection',
                'verbose_name_plural': 'Détections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='app.module')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
